on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions: read-all

concurrency: "e2e.installer-action"

env:
  # UPDATE ON RELEASE: version.
  LATEST_VERSION: v2.7.0
  GH_TOKEN: ${{ secrets.E2E_GENERIC_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-verifier

jobs:
  installer:
    runs-on: ubuntu-latest
    steps:
      # Install at tag.
      # UPDATE ON RELEASE: tag.
      - uses: slsa-framework/slsa-verifier/actions/installer@v2.7.1
      - run: |
          version=$(slsa-verifier version 2>&1 | grep GitVersion | cut -d ':' -f2 | tr -d "[:space:]")
          [ "$version" == "${LATEST_VERSION:1}" ]

      - run: |
          binary_path=$(which slsa-verifier)
          rm -rf "$binary_path"

      # Install at commit.
      # UPDATE ON RELEASE: commit sha.
      - uses: slsa-framework/slsa-verifier/actions/installer@ea584f4502babc6f60d9bc799dbbb13c1caa9ee6 # v2.7.1
      - run: |
          version=$(slsa-verifier version 2>&1 | grep GitVersion | cut -d ':' -f2 | tr -d "[:space:]")
          [ "$version" == "${LATEST_VERSION:1}" ]

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [installer]
    if: needs.installer.result == 'success'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: ./.github/workflows/scripts/e2e-report-success.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [installer]
    if: always() && needs.installer.result == 'failure'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
