on:
  # Only triggered manually for pre-release.
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    # Update the reference in this line with the builder's version to test.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.1.0
    with:
      go-version: "1.24"
      config-file: .github/configs-go/config-noldflags.yml

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build]
    if: needs.build.result == 'success'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |
          set -euo pipefail

          echo "This test should fail"
          exit 1
